"""Keep the dashboard, source inspector, and portable model metadata in sync."""
import json
import shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
target=ROOT/'frontend/src/data'
for name,source in [('training_history.json','checkpoints'),('tokenizer.json','data'),('corpus.txt','data'),('dataset_manifest.json','data')]:
    shutil.copyfile(ROOT/'backend'/source/name,target/name)
code='// Generated by scripts/sync_artifacts.py; do not edit by hand.\n'
for label,name in [('MODEL_CODE','model.py'),('TRAIN_CODE','train.py')]:
    code+=f'export const {label} = '+json.dumps((ROOT/'backend'/name).read_text())+';\n'
(target/'codebase.ts').write_text(code)
