"""Keep the dashboard, source inspector, and portable model metadata in sync."""
import json
import shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
target=ROOT/'frontend/src/data'
for name,source in [('training_history.json','checkpoints'),('tokenizer.json','data'),('corpus.txt','data'),('dataset_manifest.json','data')]:
    shutil.copyfile(ROOT/'backend'/source/name,target/name)
code='// Generated by scripts/sync_artifacts.py; do not edit by hand.\n'
for label,name in [('MODEL_CODE','model.py'),('TRAIN_CODE','train.py')]:
    code+=f'export const {label} = '+json.dumps((ROOT/'backend'/name).read_text())+';\n'
(target/'codebase.ts').write_text(code)
reports = {}
for key, name in [('held_out', 'evaluation.json'), ('canonical', 'canonical_evaluation.json')]:
    path = ROOT/'docs'/name
    if path.exists():
        data=json.loads(path.read_text())
        reports[key]={k:data[k] for k in ['exact_matches','total_prompts','exact_match_rate','scope']}
if reports:
    (target/'generation_benchmark.json').write_text(json.dumps(reports,indent=2)+'\n')
documents=json.loads((ROOT/'backend/data/train.json').read_text())
topics={}
for document in documents:
    topics.setdefault(document['topic'],document['question'])
(target/'curriculum_topics.json').write_text(json.dumps([{'topic':topic,'question':question} for topic,question in topics.items()],indent=2)+'\n')
